name: MagicCostume
version: '${version}'

main: org.psyrioty.magicCostume.MagicCostume
api-version: '1.21.11'
load: POSTWORLD
softdepend: [MagicModels]

commands:
  costume:
    description: MagicCostume plugin commands
    usage: /costume
    permission: group.default
    permission-message: "Not permission"
